name: Deploy SvelteKit (Self-hosted)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install and Build
        run: |
          # --global から --system に変更
          sudo git config --system --add safe.directory /opt/atserver186.jp

          cd /opt/atserver186.jp
          git pull origin main
          npm install
          npm run build
          pm2 restart web01 || pm2 start build/index.js --name web01
